### PR TITLE
Setup tests

### PR DESCRIPTION
**Pull request by canyener**
Set tests and github actions for the repo.
Hope this one helps ❤️

### CODE REVIEW

**Comment by hasankemaldemirci** [comment]
> Set tests and github actions for the repo.
> Hope this one helps ❤️

Thank you for contribution @canyener ✨

**Comment by canyener** [comment]
> > Set tests and github actions for the repo.
> > Hope this one helps ❤️
> 
> Thank you for contribution @canyener ✨

**Comment by canyener** [comment]
> > Set tests and github actions for the repo.
> > Hope this one helps ❤️
> 
> Thank you for contribution @canyener ✨

No you! 👍

**Comment by canyener** [comment]
> Great effort bro 👍 ✨

Glad it helped, thanks man! 👍 🎧

**Pull request merged**
